apiVersion: v1
kind: Pod
metadata: 
 name: mayankpod
 labels: 
  run: mayankppod
spec: 
 containers: 
 - command: ["/bin/sh", "-c", "ping 8.8.8.8 > /opt/number.out "]
   image: busybox
   name: mayankcont
   volumeMounts: 
   - mountPath: /opt
     name: mayank 
 volumes: 
 - name: mayank
   persistentVolumeClaim: 
    claimName: mypvc
